# Generated by Django 5.2 on 2026-08-05 16:22

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(max_length=280, unique=True, verbose_name='Slug')),
                ('brand', models.CharField(blank=True, max_length=120, verbose_name='Brand')),
                ('featured_image', models.ImageField(blank=True, upload_to='products/featured/', verbose_name='Featured image')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='Short description')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))], verbose_name='Rating')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='Review count')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('AMAZON', 'Amazon'), ('FLIPKART', 'Flipkart')], max_length=20, verbose_name='Platform')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Price')),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='MRP')),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Discount percent')),
                ('affiliate_url', models.URLField(max_length=2048, verbose_name='Affiliate URL')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product price',
                'verbose_name_plural': 'Product prices',
                'ordering': ['product', 'platform'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='prod_cat_active_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='prod_brand_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='prod_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['platform'], name='price_platform_idx'),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['last_updated'], name='price_last_updated_idx'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.UniqueConstraint(fields=('product', 'platform'), name='unique_product_platform_price'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='product_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.CheckConstraint(condition=models.Q(('mrp__gte', 0), ('mrp__isnull', True), _connector='OR'), name='product_price_mrp_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 100)), name='product_price_discount_range'),
        ),
    ]
