# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="marketplace_image_url",
            field=models.URLField(
                blank=True,
                help_text="Remote Amazon or Flipkart image URL; used before the uploaded image.",
                max_length=2048,
                verbose_name="Marketplace image URL",
            ),
        ),
    ]
