# Generated by Codex on 2026-08-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="display_order",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                verbose_name="Display order",
            ),
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["display_order", "name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.RemoveIndex(
            model_name="category",
            name="cat_active_name_idx",
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["is_active", "display_order", "name"],
                name="cat_nav_order_idx",
            ),
        ),
    ]
