# Generated by Django 5.2 on 2026-08-09 14:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asin', models.CharField(max_length=20, unique=True)),
                ('product_title', models.TextField(blank=True)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(max_length=1000)),
                ('availability', models.CharField(blank=True, max_length=255)),
                ('images', models.JSONField(blank=True, default=list)),
                ('mrp_inr', models.PositiveIntegerField(blank=True, null=True)),
                ('current_selling_price_inr', models.PositiveIntegerField(blank=True, null=True)),
                ('selling_price_min_inr', models.PositiveIntegerField(blank=True, null=True)),
                ('selling_price_max_inr', models.PositiveIntegerField(blank=True, null=True)),
                ('discount_percentage', models.PositiveIntegerField(blank=True, null=True)),
                ('primary_seller', models.CharField(blank=True, max_length=255)),
                ('seller_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('processor', models.CharField(blank=True, max_length=255)),
                ('ram', models.CharField(blank=True, max_length=255)),
                ('storage', models.CharField(blank=True, max_length=255)),
                ('operating_system', models.CharField(blank=True, max_length=255)),
                ('display_size', models.CharField(blank=True, max_length=255)),
                ('resolution', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(blank=True, max_length=255)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('software', models.CharField(blank=True, max_length=255)),
                ('warranty', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('extracted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
