# Generated by Django 5.2 on 2026-08-09 15:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0002_amazonproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlipkartSearchResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pid', models.CharField(db_index=True, max_length=100)),
                ('title', models.TextField()),
                ('product_url', models.URLField(max_length=1000)),
                ('position', models.PositiveIntegerField()),
                ('sponsored', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amazon_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flipkart_results', to='importer.amazonproduct')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('amazon_product', 'pid'), name='unique_flipkart_candidate_per_amazon_product')],
            },
        ),
    ]
