# Generated by Django 5.2 on 2026-08-09 15:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0004_flipkartproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=10)),
                ('match_status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('rejected', 'Rejected'), ('review', 'Review')], default='pending', max_length=10)),
                ('reasons', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amazon_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_matches', to='importer.amazonproduct')),
                ('flipkart_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_matches', to='importer.flipkartproduct')),
            ],
            options={
                'ordering': ['-score', '-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('amazon_product', 'flipkart_product'), name='unique_product_match_pair'), models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 100)), name='product_match_score_between_0_and_100')],
            },
        ),
    ]
