# Generated by Django 5.2 on 2026-08-09 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_display_order'),
        ('importer', '0005_productmatch'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productmatch',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmatch',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_importer_product_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productmatch',
            name='publish_category',
            field=models.ForeignKey(blank=True, help_text='Active category required before publishing to the live catalog.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='importer_product_matches', to='categories.category'),
        ),
        migrations.AddField(
            model_name='productmatch',
            name='publish_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productmatch',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmatch',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_importer_product_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productmatch',
            name='published_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importer_product_matches', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productmatch',
            name='match_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('rejected', 'Rejected'), ('review', 'Review'), ('approved', 'Approved'), ('published', 'Published'), ('publish_failed', 'Publish failed')], default='pending', max_length=20),
        ),
    ]
