# Generated by Django 5.2 on 2026-08-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0006_productmatch_approved_at_productmatch_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchkeyword',
            name='matching_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of matching completed staging products for this keyword.', max_length=20),
        ),
    ]
