# Generated by Django 5.2 on 2026-08-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_display_order'),
        ('importer', '0007_searchkeyword_matching_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmatch',
            name='publish_categories',
            field=models.ManyToManyField(blank=True, help_text='Active categories selected during review; the first is primary.', related_name='importer_product_match_categories', to='categories.category'),
        ),
    ]
