# Generated by Django 5.2 on 2026-08-09 18:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0008_productmatch_publish_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('amazon_search', 'Amazon Search'), ('amazon_extraction', 'Amazon Extraction'), ('flipkart_search', 'Flipkart Search'), ('flipkart_extraction', 'Flipkart Extraction'), ('matching', 'Matching'), ('ready_for_review', 'Ready for Review'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=30)),
                ('amazon_results_count', models.PositiveIntegerField(default=0)),
                ('amazon_products_count', models.PositiveIntegerField(default=0)),
                ('flipkart_results_count', models.PositiveIntegerField(default=0)),
                ('flipkart_products_count', models.PositiveIntegerField(default=0)),
                ('matches_count', models.PositiveIntegerField(default=0)),
                ('successful_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='importer.searchkeyword')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='batches',
            field=models.ManyToManyField(blank=True, related_name='amazon_products', to='importer.importbatch'),
        ),
        migrations.AddField(
            model_name='amazonsearchresult',
            name='batches',
            field=models.ManyToManyField(blank=True, related_name='amazon_search_results', to='importer.importbatch'),
        ),
        migrations.AddField(
            model_name='flipkartproduct',
            name='batches',
            field=models.ManyToManyField(blank=True, related_name='flipkart_products', to='importer.importbatch'),
        ),
        migrations.AddField(
            model_name='flipkartsearchresult',
            name='batches',
            field=models.ManyToManyField(blank=True, related_name='flipkart_search_results', to='importer.importbatch'),
        ),
        migrations.AddField(
            model_name='productmatch',
            name='batches',
            field=models.ManyToManyField(blank=True, related_name='product_matches', to='importer.importbatch'),
        ),
    ]
