# Generated by Django 5.2

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_category_display_order"),
        ("importer", "0010_add_search_keyword_to_flipkart_search_result"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="amazonproduct",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="amazonproduct",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="amazonproduct",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_amazon_products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="amazonproduct",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="amazonproduct",
            name="published",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="amazonproduct",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="amazonproduct",
            name="published_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="amazon_products",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="amazonproduct",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Categories selected for the public catalog; the first is primary.",
                related_name="amazon_products",
                to="categories.category",
            ),
        ),
        migrations.AlterField(
            model_name="amazonproduct",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
