# Generated by Django 5.2

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_category_display_order"),
        ("importer", "0011_amazonproduct_publishing"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="flipkartproduct",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="flipkartproduct",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="flipkartproduct",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_flipkart_products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="flipkartproduct",
            name="published",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="flipkartproduct",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="flipkartproduct",
            name="published_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flipkart_products",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="flipkartproduct",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Categories selected for the public catalog; the first is primary.",
                related_name="flipkart_products",
                to="categories.category",
            ),
        ),
    ]
