# Generated by Django 5.2 on 2026-08-14 20:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0012_flipkartproduct_publishing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImporterJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('amazon_search', 'Amazon Search'), ('amazon_product_extraction', 'Amazon Product Extraction'), ('flipkart_search', 'Flipkart Search'), ('flipkart_product_extraction', 'Flipkart Product Extraction'), ('best_match_flipkart', 'Best-Matched Flipkart'), ('product_matching', 'Product Matching'), ('product_publishing', 'Product Publishing')], db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('marketplace', models.CharField(blank=True, choices=[('amazon', 'Amazon'), ('flipkart', 'Flipkart'), ('both', 'Amazon + Flipkart'), ('internal', 'Internal')], db_index=True, max_length=20)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('processed_items', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('result_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amazon_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importer_jobs', to='importer.amazonproduct')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importer_jobs', to=settings.AUTH_USER_MODEL)),
                ('flipkart_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importer_jobs', to='importer.flipkartproduct')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importer_jobs', to='importer.importbatch')),
                ('product_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importer_jobs', to='importer.productmatch')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'status'], name='importer_im_created_d41dc1_idx'), models.Index(fields=['job_type', 'status'], name='importer_im_job_typ_5a8431_idx')],
            },
        ),
    ]
