# Generated by Django 5.2 on 2026-08-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0013_importerjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonproduct',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='highlights',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='specifications',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
