# Generated by Django 5.2 on 2026-08-15 21:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0014_amazonproduct_description_amazonproduct_highlights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchkeyword',
            name='amazon_pages',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of Amazon result pages to request.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='searchkeyword',
            name='amazon_sorting',
            field=models.CharField(choices=[('relevanceblender', 'Featured / Relevance'), ('exact-aware-popularity-rank', 'Best Seller'), ('date-desc-rank', 'New Arrivals'), ('review-rank', 'Avg. Customer Review'), ('price-desc-rank', 'Price: High to Low'), ('price-asc-rank', 'Price: Low to High')], default='relevanceblender', max_length=64),
        ),
        migrations.AddField(
            model_name='searchkeyword',
            name='amazon_sorting_label',
            field=models.CharField(default='Featured / Relevance', editable=False, max_length=100),
        ),
    ]
